# Generated by Django 4.1.4 on 2023-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobCategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferredQualification',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
