# Generated by Django 3.2.18 on 2023-02-15 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_job_jobcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 2, 15)),
        ),
    ]
