# Generated by Django 4.1.7 on 2023-04-13 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20230215_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
    ]
